### PR TITLE
copied content

### PR DESCRIPTION
**Pull request by itamar-reiter**

### CODE REVIEW

**Comment by FiLLa-FaS** [comment]
Hey! Thank you for sending your project for review, it already looks very good. I especially like your responsive layout, the page looks very good on breakpoints and intermediate screen resolutions. Btw there're several issues below, please fix them to get more points and improve your project. Good luck!✨

# Summary:
### Performance Criteria

- [x]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout and get out of the grid in the layout.
    * You need to link all font-faces correctly (each non-variable font file should be related with `font-weight` with correct value)
    * Incorrect distance between `search-form__subtitle` and `search-form__form` on 768 viewport
    * Incorrect bottom padding of `search-form` on 768 viewport
    * Incorrect width of `search-form__submit-button` on 768 viewport
    * Incorrect distance between footer and the end of the page on 768 viewport
    * Background of header should be changed when nav menu is opened https://skr.sh/sHyfyCl0RPd?a
    * Incorrect distance between the start of `about` and `about__image` on 320 viewport
    * Cards should be adapted for any content size https://skr.sh/sHy1SuIzFT4?a
    * There should be a line between the header and the rest content https://skr.sh/sHyO4KhFS2S?a https://skr.sh/sHylAuob3Lk?a
- [x]  The project is adapted for different screen resolutions and looks correctly on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
    * Navigation between main and saved-articles pages doesn't work by clicking at header links
    * Footer links are not working
- [x]  Classes are named according to BEM specifications.
    * `popup__relative-path_link-style`, `popup__content_success-register` and all `..._in-saved-news` modifiers should be a key-value modifiers instead of boolean
    * All modifiers should be written with its base classes `block__element block__element_key_value`
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
    * Each page can have only one `h1` tag
    * `popup__relative-path_link-style` should be a link or button
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [ ]  There are no linting errors or warnings.
    * https://skr.sh/sHyd8QBHGab?a

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
    * No marked state of the card buttons https://skr.sh/sHy9LjpsB8L?a
    * No click state of search submit button https://skr.sh/sHyCFND3Byn?a
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
    * `popup__relative-path_link-style` and popup submit button should be highlighted
- [x]  The form must have placeholders,  and there are required properties for the fields.
    * You need to add basic validation for popup inputs
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [ ]  System fonts are connected as alternatives to each of your fonts.
    * No alternative fonts or generic families https://skr.sh/sHyuOGSymCJ?a
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 54

**Comment by itamar-reiter** [comment]
i cant understand whats wrong with the links. on localhost it doesnt work, but on my VM instance it works

https://itamarreiter.newsexplorer.students.nomoredomainssbs.ru/

**Comment by FiLLa-FaS** [comment]
Hey! I'm sorry for the delay with response, but I think you should try to discuss this issue with your mentors and find a good way to resolve this. Good luck!

**Comment by itamar-reiter** [comment]
hey! added some changes

**Comment by FiLLa-FaS** [comment]
Hey! Congratulations, you've got more than 80 points, so your project has been accepted! Btw there're still several small issues below, you can fix them to improve your project even more. Good luck on the next diploma stage!🚀

# Summary:
### Performance Criteria

- [x]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout and get out of the grid in the layout.
- [x]  The project is adapted for different screen resolutions and looks correctly on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
- [ ]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
    * Footer facebook link should lead to an actual website
- [x]  Classes are named according to BEM specifications.
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [ ]  There are no linting errors or warnings.
    * https://skr.sh/sI3j7OtIaCA?a https://skr.sh/sI3IldcTmsc?a

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [ ]  System fonts are connected as alternatives to each of your fonts.
    * No alternative fonts or generic families https://skr.sh/sHyuOGSymCJ?a
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 82

**Pull request merged**
